### ISSUE TITLE
Installing on Fedora (F24, python 3.7 altinstall)

### ISSUE THREAD

**Issue by ntavares** [ericmandel/pyds9#101]
Hi fellows,

Thank you for the package. I'm suggesting to improve the documentation in regards to the installation. On a fresh python setup (altinstall), I struggled a bit (not much) to get this going... maybe this info can be of any help.

Distribution: Fedora 24 (pretty old, but this will probably apply to more recent ones)
Python: 3.7 (altinstall)

pip3.7 install pyds9 would fail with:
```
    gcc -c -I. -g -O2 -fPIC -DHAVE_CONFIG_H  xtloop.c
    xtloop.c:9:27: fatal error: X11/Intrinsic.h: No such file or directory
     #include <X11/Intrinsic.h>
                               ^
    compilation terminated.
    Makefile:405: recipe for target 'xtloop.o' failed
    make: *** [xtloop.o] Error 1
    creating build
    creating build/lib
    copying pyds9.py -> build/lib
    copying xpa.py -> build/lib
    running install_lib
    running install_data
    Installing data files to /usr/local/lib/python3.7/site-packages/
    error: can't copy 'xpa/libxpa.so': doesn't exist or not a regular file
```
I've installed xpa separately, but I think what was missing was:
```
$ dnf install libXt-devel
$ rpm -ql libXt-devel | grep Intrinsic.h
/usr/include/X11/Intrinsic.h
```
After this the library installed fine. I know python/pip has nothing to do with distribution package managers, but maybe this info could fit somewhere in the documentation or something.

Hope this helps.
-NT

**Comment by ericmandel** [comment]
@ntavares Thanks very much, I added a line about Fedora to the README (we already had Ubuntu and openSUSE).
