### ISSUE TITLE
TypeError when running Setup.py on Mac OS X Monterey

### ISSUE THREAD

**Issue by Logic-Beach** [ericmandel/pyds9#102]
`Traceback (most recent call last):
  File "/Users/logicbeach/pyds9/setup.py", line 45, in <module>
    cmdclassd = register_commands()
TypeError: register_commands() missing 3 required positional arguments: 'package', 'version', and 'release'`

**Comment by ericmandel** [comment]
@Logic-Beach Sorry, but as noted on the main pyds9 page, we have no Python maintainer for pyds9 to work on issues such as this one.

**Comment by Logic-Beach** [comment]
Ah, I see. I actually have DS9 working via x11, but having it operable from my python script would be nice, you can close this if you want. I may poke around on my own and see if I can fix it... no promises.

**Comment by ericmandel** [comment]
Yes, thanks, PRs are welcome!
