### ISSUE TITLE
XPA Error 

### ISSUE THREAD

**Issue by maelstromscientist** [ericmandel/pyds9#12]
When I attempt to send a .fits image file to pyds9 I get the following error message:

ValueError: XPA$ERROR undefined command for this xpa (DS9:ds9 7f000101:33016)

I should note that I am using the latest version of Ubuntu (if that helps).  This error only occurs when I try to set a .fits image to ds9.  I can still successfully send an array to ds9 (via set_np2arr()), and it displays perfectly.  

Any suggestions?

**Comment by ericmandel** [comment]
The error indicates that you are not passing the "fits" argument in the param list. I believe this xpa access point requires two args: "fits" in the param list and the actual fits data in the data arg. If this is not the problem, please tell me the args you are passing.

**Comment by maelstromscientist** [comment]
Ah that solved the problem.  Thank you!
