### ISSUE TITLE
passing parameters to the constructor

### ISSUE THREAD

**Issue by mherkazandjian** [ericmandel/pyds9#13]
Hi, 

I was trying to launch an instance of DS9 using:

> from pyds9 import DS9
> d = DS9('-geometry 1920x1080')

This seems to cause some confusion. I think it would be useful to add a keyword to the constructor that passes the arguments that would otherwise be used to launch ds9 from the command line to Popen.  I patched this locally. So now i can do the following:

> d = DS9(parms='-geometry 1920x1080')

Thisway there is a clear distinction between the pyds9.DS9 keywords and the parameters passed in launching 'ds9' itself.

cheer,
mher.

**Comment by ericmandel** [comment]
The 'start' parameter already does this:

    d = pyds9.DS9(start="-cmap red -scale log -geometry 1920x1080")

**Comment by mherkazandjian** [comment]
cool. i missed that. tnx.
