### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by cdeil** [ericmandel/pyds9#15]
Triggered by some discussions in #14, I'd like to suggest to set up continuous integration.

Probably best to start with Linux on travis-ci.
Mac OS X testing on travis-ci and Windows testing on Appveyor can come later.

One possibility is to copy over the CI setup files from Astropy:
https://github.com/astropy/astropy
or of course one can start a `.travis.yml` file from scratch.

This can start small and simple ... just check that `python setup.py install` and `import pyds9` works on Python 2 and 3. Adding and executing tests can then come in later PRs.

@ericmandel I think you have to head over to https://travis-ci.org/ and activate testing for this repo first.
Then I can try adding the test setup files here.

**Comment by montefra** [comment]
@ericmandel : I enabled Travis CI on my copy of pyds9. In the next days I'll work on it. This way we can at least test the installation and import on Linux and MacOSX under various settings.

Once I'm done there I'll need you to enable Travis here.

**Comment by ericmandel** [comment]
@montefra That's a good idea ... instructions for turning it on will be welcome when the time comes ...

**Comment by montefra** [comment]
@ericmandel : I have explore travis-ci and played with it. There are a couple of failures I don't understand yet, but I would like to enable it.
To enable travis-ci it's enough to do the following (I think you already enabled it for pyjs9 a year ago):
* go to https://travis-ci.org
* log in with your github account
* It should show you a page with the list of your repositories. If it doesn't show click on your name on the upper right corner of the page
* search in the page ``ericmandel/pyds9`` and flick the repository switch on
* Click on the repository name. On the right there is a "More options" menu:
  * Click on "Settings"
  * Make sure that the "Build pushes" and "Build pull requests" are enabled.

Once is up and running, I'll do a PR and let's see how it goes.

**Comment by ericmandel** [comment]
@montefra  Done. I'll be interested in hearing what tests you add to the automatic checking. We probably should add something similar to pyjs9, although it has a much simpler build.

**Comment by montefra** [comment]
@ericmandel : right now there is still no test. I just make sure that pyds9 builds and can be imported.
I'll add tests later on. I first need to make installation and import work in windows. I'll use appveyor to do it.

**Comment by ericmandel** [comment]
@montefra yes, I'm sure it will be beneficial to have the builds checked automatically. Other tests might be less useful. I tried writing meaningful tests for js9 using selenium-webdriver and it took a lot of time, relative to the overall value.

**Comment by montefra** [comment]
travis-ci and appveyor are setup and used
