### ISSUE TITLE
devel branch?

### ISSUE THREAD

**Issue by montefra** [ericmandel/pyds9#23]
Before I start reshaping the repository #19 and moving the setup script from ``distutils`` to ``setuptools`` #18 I would like to share some thought.

At the moment we don't have `pyds9` on PyPI, so people are likely using the master branch as "stable" installation.

The above changes are substantial and might break something. Plus I would prefer to present the changes all at once to the users.

So I'm thinking to start a ``devel`` branch and to develop #18 and #19 against it. Once they'll be ready and we'll be satisfied, I'll merge ``devel`` into ``master`` and call it a release.

At that point we can go on PyPI. The versions there will be the stable ones and all the development can proceed against ``master`` as usual.

Any comment?

**Comment by ericmandel** [comment]
I think this is a good idea, mainly in order to allow you to present all
changes at once. I don't know that a devel branch would get enough traffic
to "prove" that everything works properly -- instead, it might give you a
false sense of security. But I do think there is a lot of good reason to
make a branch that you can play with and build up slowly before making a
commit to the master. So, in sum, I think you should do this.

**Comment by cdeil** [comment]
@montefra – If you really think "people are likely using the master branch as "stable" installation", why not tag master and make a release on PyPI right now? And then continue development in master like pretty much all project on Github?

But that's just my 2 cents ... in the end I don't think it matters in which branch you develop in the near future ... the important thing is that it's happening at all. Thank you, @montefra!

**Comment by montefra** [comment]
@ericmandel:

> to "prove" that everything works properly -- instead, it might give you a
false sense of security.

There is only one way for it: unit tests. Independently of the branch name. We will work on it, eventually.

@cdeil : I would personally wait to have the code organized in a more standard way and that uses setuptools before going to PyPI.

**Comment by ericmandel** [comment]
> the important thing is that it's happening at all. Thank you, @montefra!

I fully agree!

**Comment by montefra** [comment]
done

**Comment by montefra** [comment]
This is a check list for me to check what I should do and for whoever wants to follow/comment:

[ ] reformat the directory structure #19, #24 
[ ] move to setuptools #18, #24 
[ ] relicense xpa and pyds9 to MIT #25; add xpa as submodule?
[ ] move the test function to the test directory and integrate it with pytest
[ ] setup continuous integration #15 
[ ] make the documentation work

**Comment by montefra** [comment]
Now that pyds9 is back in a usable state, I've merged devel into master and I'll keep working from there.
