### ISSUE TITLE
Get projection profile with pyds9

### ISSUE THREAD

**Issue by duyhoang2014** [ericmandel/pyds9#31]
Hi Developers,

I am not sure if I should call this issue or not. Perhaps just a question. In ds9 I can get data (profile) along a projection region from an image. I can do this by 'clicking' which takes a lot of time if I have many regions. Scripting these clicks could save quite a lot of time. I am wondering if there is any way to do the same with pyds9?

Thanks,
Duy

**Comment by ericmandel** [comment]
Since pyds9 is able to call all of the XPA public access routines implemented by DS9, I believe this is a question best answered by @wjoye or @saoimageds9. Hopefully, we will hear from Bill Joye (DS9 author) soon.

**Comment by wjoye** [comment]
Currently, invoking an analysis task in ds9 via XPA is not supported. This item is on the to-do list, and hopefully will be addressed sooner than later.

**Comment by duyhoang2014** [comment]
Thanks ericmandel, wjoye for the quick reply. It's good to hear that it is on the to-do list. Thanks.
