### ISSUE TITLE
Installation Problems on Windows 10 with Anaconda

### ISSUE THREAD

**Issue by cjbohlman** [ericmandel/pyds9#45]
Hi, I am currently running Python 3.5 through Anaconda on a Windows 10 device.

When I am installing pyds9 through the zip file, and using the command
`python setup.py install`
I come across the following error:

```
Traceback (most recent call last):
  File "c:\users\chris\documents\pyds9-master\pyds9-master\.eggs\astropy_helpers-1.2-py3.5.egg\astropy_helpers\setup_helpers.py", line 285, in run_command_hooks
    hook_obj(cmd_obj)
  File "pyds9\setup_package.py", line 87, in pre_build_ext_hook
    libxpa = cmd.ext_map['pyds9.libxpa']
  File "C:\Users\Chris\Anaconda3\lib\site-packages\Cython\Distutils\build_ext.py", line 135, in __getattr__
    return _build_ext.build_ext.__getattr__(self, name)
  File "C:\Users\Chris\Anaconda3\lib\distutils\cmd.py", line 103, in __getattr__
    raise AttributeError(attr)
AttributeError: ext_map
```

What does this mean, and how can I circumvent this? I've tried various other fixes, including installing MinGW and getting pyds9 through the Git repository.

Thank you!

**Comment by montefra** [comment]
@cbohlmanaz: Thank for the report. #46 report similar problems on linux and opensuse using anaconda.

In the meanwhile I suggest using the released version (v1.8.1).

**Comment by montefra** [comment]
Can you please tell me the version of Cython that you have on your system?

**Comment by wjoye** [comment]
Ok, I'm back in the office. I have a Windows 10 VM setup, so I can do any testing. Just let me know. Aside, I also have VMs for Ubuntu (16, 14), Centos (7, 6), and MacOSX (10.11, 10.10, 10.9)

**Comment by montefra** [comment]
@wjoye : thank you very much for the offer. I've asked support to the [astropy-dev mailing list](https://groups.google.com/forum/#!topic/astropy-dev/YkHSK6uQV5w). The issues seems to be Cython interacting with some part of the astropy-helpers machinery and then invoking the wrong command objects.

I hope that they have some advice.

**Comment by montefra** [comment]
On my system PR #48 solves the problem. I'll merge the PR soon.
However I want to setup Travis CI first at least to test installation. I am planning to add appveyor for Windows testing afterwards.

If you want to test the installation, you can do it with:

pip install git+https://github.com/montefra/pyds9.git@install_cython#eggs=pyds9

However I don't think that pyds9 will work before I merge #44.

**Comment by cbohlmanaz** [comment]
So good news, I no longer get that error!
However, I get a different one, unfortunately. It reads:
`Traceback (most recent call last):
      File "c:\users\chris\appdata\local\temp\pip-build-9756r3vx\pyds9\astropy_helpers\astropy_helpers\setup_helpers.py", line 285, in run_command_hooks
        hook_obj(cmd_obj)
      File "pyds9\setup_package.py", line 94, in pre_build_ext_hook
        sp.check_call([os.path.join('.', 'configure'), '--without-tcl'])
      File "C:\Users\Chris\Anaconda3\lib\subprocess.py", line 576, in check_call
        retcode = call(*popenargs, **kwargs)
      File "C:\Users\Chris\Anaconda3\lib\subprocess.py", line 557, in call
        with Popen(*popenargs, **kwargs) as p:
      File "C:\Users\Chris\Anaconda3\lib\subprocess.py", line 947, in __init__
        restore_signals, start_new_session)
      File "C:\Users\Chris\Anaconda3\lib\subprocess.py", line 1224, in _execute_child
        startupinfo)
    OSError: [WinError 193] %1 is not a valid Win32 application`

It seems to be referring to a .py file that is not executable, and after looking at it for awhile and doing some research online, I'm really unsure about what to do...
Is this an error on my machine, or something like that? 
Thank you!

**Comment by montefra** [comment]
@cbohlmanaz : Thank you for testing.
I know about your new error. I fixed that in my branch ``windows`` that you can see in #44.

Right now I am fighting with appveyor to get pyds9 to work on windows.
I have no idea of how windows work and up to now the experience is very frustrating.
I have no idea if that is a problem of pyds9, astropy_helpers or appveyor.
If you have any suggestion, don't hesitate to comment in that PR.

**Comment by MRashidRamzan** [comment]
Step 1: Before uninstalling Anaconda use this command 
anaconda-clean --yes
Step 2: Delete All files e.g .conda  .anaconda etc
Step 3: Uninstall Anaconda 
Step 4: install it Again InShaAllah there will be no Error
