### ISSUE TITLE
pyds9.py and python3

### ISSUE THREAD

**Issue by paegert** [ericmandel/pyds9#64]
Python 3 complains about concatenating bytes to strings when creating error messages. Lines similar to 
`errmsg += ctypes.string_at(errs[i]).strip() + '\n'`
should be replaced by
`errmsg += str(ctypes.string_at(errs[i]).strip()) + '\n'`

**Comment by montefra** [comment]
@paegert : thank you for the report.

Can you provide us more information? The traceback or warning and if possible the command that triggers the error are sufficient.

I think that I know what you are referring to, but would be nice to have a confirmation.

**Comment by DougBurke** [comment]
Closed by #88 (hopefully)
