### ISSUE TITLE
Activate problem in anaconda

### ISSUE THREAD

**Issue by partha1968** [ericmandel/pyds9#66]
I am using windows 10 (64 bit) and installed Anaconda Python. I am getting following error.
How to solve this ?
Regards
parth

Unable to create process using 'C:\Users\Partha\Anaconda3\python.exe C:\Users\Partha\Anaconda3\Scripts\conda-script.py shell.cmd.exe activate activate C:\Users\Partha\Anaconda3'

**Comment by montefra** [comment]
@partha1968 this does not seem a problem with ``pyds9``. This is the wrong repository to report the problem
