### ISSUE TITLE
Pyfits and astropy.io.fits

### ISSUE THREAD

**Issue by fmerges** [ericmandel/pyds9#73]
Hello,

I can see on the top of the file, it's importing from astropy.io the fits module, but later on in the code there are references to pyfits module, and two methods that uses it.

Shouldn't this be refactored?

https://github.com/ericmandel/pyds9/blob/c1bf67ab195bd7eb0c662755c2df35df014482b0/pyds9/pyds9.py#L121-L130

Cheers,

Florian

**Comment by montefra** [comment]
This is more or less legacy code for the time before ``astropy.io.fits`` exists. The ``get_pyfits`` and ``set_pyfits`` methods uses pyfits if found, otherwise fall back to astropy's fits.

I think that the refactoring will be to eventually remove pyfits

**Comment by DougBurke** [comment]
Closed by #87
