### ISSUE TITLE
Error in last commit 

### ISSUE THREAD

**Issue by vpicouet** [ericmandel/pyds9#75]
Hi, 
I think there is a ':' missing in the last commit (12th of february).
![image](https://user-images.githubusercontent.com/37241971/52714901-5f7d6300-2f9b-11e9-8a38-ed029f5763e3.jpeg)
It does not prevent the installation but prevent to import the package.

Cheers

Vincent

**Comment by montefra** [comment]
@vpicouet thank you for spotting this. I've made PR #76 to address the problem.

The fact is that the tests are currently broken and I don't know why and how to fix it. So this slipped past me. I'll merge the PR asap.

**Comment by montefra** [comment]
the semicolon bug is now fixed
