### ISSUE TITLE
./ds9: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by M-Thirumal** [ericmandel/pyds9#79]
Not able to run the file in ubuntu 19.04

`
 ./ds9: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

**Comment by wjoye** [comment]
Please use DS9 version 8.1b2:
http://ds9.si.edu/site/Beta.html

This version no longer requires external ssl libs.
