### ISSUE TITLE
Wanted: new maintainer 

### ISSUE THREAD

**Issue by montefra** [ericmandel/pyds9#80]
Dear Eric, dear everyone,

as you clearly noticed, I am not active anymore.
Having left astronomy one and a half years ago, took away the main drive in maintaining pyds9. Plus having a new jobs made things more complicated.
I have tried to do something every now and them, but without too much success.

I should have written this long ago and not drag it longer than necessary.

I enjoyed working for the project and I learned a lot doing it. I thank @ericmandel for "volunteering" me and giving me the chance to do something new and different.
I hope that the project can find a maintainer more dedicated than myself and that it keeps living.

Cheers,
Francesco

**Comment by ericmandel** [comment]
Dear Francesco,

The whole astro/python community owes you a debt of gratitude for all the work you did on pyds9. I am very grateful for your efforts. I'll cc this to some potentially interested parties ... hopefully someone will come forward to fill the void created by your leaving. Thank you again for all your work!

cc: @eteq @cdeil @DougBurke @astrofrog @augustfly @taldcroft @hamogu @wjoye @kglotfelty

**Comment by wjoye** [comment]
I’ll step forward if no one would like the job.

bill

**Comment by ericmandel** [comment]
Thanks, @wjoye, I've added you to the collaborator list ... at least you should see the issues that arise and have the ability to comment. But I should mention that @montefra's efforts were mainly concerned with maintaining the Python-specific code ... in case that is not your area of expertise.

**Comment by cdeil** [comment]
@montefra @ericmandel @wjoye - Thank you!
(I don't have time to contribute.)

**Comment by DougBurke** [comment]
I can help maintain the Python side.

**Comment by ericmandel** [comment]
Thanks, @DougBurke, I've added you to the collaborator list.

**Comment by ericmandel** [comment]
You both have push access to the pyds9 repository ...
