### ISSUE TITLE
pyds9 - ValueError: no active ds9 running for target: ds9

### ISSUE THREAD

**Issue by supriyo-astro** [ericmandel/pyds9#99]
I am having the following errors when I try to run pyds9.

 Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyds9
>>> print(pyds9.ds9_targets())
None
>>> d = pyds9.DS9()
Error in startup script: expected integer but got ""
    (processing "-size" option)
    invoked from within
"colorbar configure  -size $colorbar(size)  -ticks $colorbar(ticks)  -numerics $colorbar(numerics)  -space $colorbar(space)  -font $colorbar(font)  -fo..."
    (procedure "LayoutColorbar" line 8)
    invoked from within
"LayoutColorbar"
    (procedure "CreateColorbar" line 29)
    invoked from within
"CreateColorbar"
    (file "zipfs:/mntpt/library/ds9.tcl" line 523)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ir/anaconda3/lib/python3.7/site-packages/pyds9/pyds9.py", line 527, in __init__
    raise ValueError('no active ds9 running for target: %s' % target)
ValueError: no active ds9 running for target: ds9

Also,
:~$ ps guwax | egrep -i ds9
ir         25021  0.0  0.0   2876  2108 pts/0    S    10:51   0:00 /home/astro/anaconda3/lib/python3.7/site-packages/pyds9/xpans -e
ir         26845  0.0  0.0      0     0 pts/2    Z    11:07   0:00 [ds9] <defunct>
ir         27231  0.0  0.0      0     0 pts/0    Z+   11:14   0:00 [ds9] <defunct>
ir         27604  0.0  0.0   9032  2636 pts/2    S+   11:21   0:00 grep -E --color=auto -i ds9

:~$ ps guwax | egrep xpans
ir         25021  0.0  0.0   2876  2108 pts/0    S+   10:51   0:00 /home/astro/anaconda3/lib/python3.7/site-packages/pyds9/xpans -e
ir         25703  0.0  0.0   9032   664 pts/2    S+   11:04   0:00 grep -E --color=auto xpans

:~$ ds9 &
[2] 27827
:~$ Error in startup script: expected integer but got ""
    (processing "-size" option)
    invoked from within
"colorbar configure  -size $colorbar(size)  -ticks $colorbar(ticks)  -numerics $colorbar(numerics)  -space $colorbar(space)  -font $colorbar(font)  -fo..."
    (procedure "LayoutColorbar" line 8)
    invoked from within
"LayoutColorbar"
    (procedure "CreateColorbar" line 29)
    invoked from within
"CreateColorbar"
    (file "zipfs:/mntpt/library/ds9.tcl" line 523)

[2]-  Exit 1                  ds9

**Comment by ericmandel** [comment]
The last test seems to indicate that ds9 is not able to start successfully on your machine, getting the same error about the -size option. @wjoye, have you seen this error before?

**Comment by wjoye** [comment]
Eric

He submitted a help desk ticket. I had him remove his prefs files and download the latest.

bill

**Comment by supriyo-astro** [comment]
Thanks a lot for your help. The problem has been resolved.
